--
-- PostgreSQL database dump
--






SET statement_timeout = 0;
SET lock_timeout = 0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- import_data_from_temporary_tables(text, text, text, text, text, text)
CREATE FUNCTION desimper.import_data_from_temporary_tables(temp_schema text, temp_table text, label_field text, value_field text, unique_id_field text, code_context text) RETURNS json
    LANGUAGE plpgsql
    AS $_$
DECLARE
    target_schema text;
    target_table text;
BEGIN

    -- Get the target table and schema from the context list
    EXECUTE format(
        $SQL$
            SELECT nom_schema, nom_table
            FROM desimper.liste_contextes
            WHERE code = %1$L
        $SQL$,
        code_context
    )
    INTO target_schema, target_table;

    IF target_table IS NULL THEN
        RETURN json_build_object(
            'status', 'error',
            'message', format('Aucune table cible pour le contexte %s', code_context)
        );
    END IF;

    -- Drop table before creating a new one
    EXECUTE format(
        'DROP TABLE IF EXISTS %1$I.%2$I CASCADE',
        target_schema,
        target_table
    );

    -- Create new table
    EXECUTE format(
        $SQL$
            CREATE TABLE %1$I.%2$I (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                unique_object_id text NOT NULL,
                geom geometry(MultiPolygon,2154) NOT NULL,
                fk_code_liste_contextes text,
                CONSTRAINT fk_code_liste_contextes FOREIGN KEY (fk_code_liste_contextes) REFERENCES desimper.liste_contextes(code),
                libelle text,
                valeur text
            )
        $SQL$,
        target_schema,
        target_table
    );    
    -- Comment on table
    -- example :
    -- id | unique_object_id | geom | fk_code_liste_contextes | libelle   | valeur
    -- 1  | 1 | MULTIPOLYGON(...)   | 'BAI' | 'Pas de site de baignade'   | 0
    -- 2  | 1 | MULTIPOLYGON(...)   | 'BAI' | 'Pas de site de baignade'   | 0
    -- 3  | 2 | MULTIPOLYGON(...)   | 'BAI' | 'Site de baignade à l'aval' | 2
    EXECUTE format(
        $SQL$
            COMMENT ON TABLE %1$I.%2$I IS %3$L;
            COMMENT ON COLUMN %1$I.%2$I.id IS 'Identifiant automatique de l''objet';
            COMMENT ON COLUMN %1$I.%2$I.unique_object_id IS 'Identifiant unique de l''objet avant la subdivision';
            COMMENT ON COLUMN %1$I.%2$I.geom IS 'Geométrie';
            COMMENT ON COLUMN %1$I.%2$I.fk_code_liste_contextes IS 'Référence le code du contexte dans la liste des contextes';
            COMMENT ON COLUMN %1$I.%2$I.libelle IS 'Libellé';
            COMMENT ON COLUMN %1$I.%2$I.valeur IS 'Valeur';
        $SQL$,
        target_schema,
        target_table,
        format('Table contenant les données pour le contexte %s', code_context)
    );

    -- Indexes : 
    -- on foreign key
    EXECUTE format(
        $SQL$
            CREATE INDEX ON %1$I.%2$I (fk_code_liste_contextes);
        $SQL$,
        target_schema,
        target_table
    );
    --on geom
    EXECUTE format(
        $SQL$
            CREATE INDEX ON %1$I.%2$I USING GIST (geom);
        $SQL$,
        target_schema,
        target_table
    );

    -- View for layer display in QGIS
    EXECUTE format(
        $SQL$
            CREATE VIEW %1$I.%2$I AS
            SELECT 
                row_number() OVER ()::integer AS id, 
                unique_object_id, ST_Union(geom) AS geom, 
                fk_code_liste_contextes, libelle, valeur
            FROM %3$I.%4$I
            GROUP BY unique_object_id, fk_code_liste_contextes, libelle, valeur
        $SQL$,
        target_schema,
        concat('v_', target_table),
        target_schema,
        target_table
    );

    -- Divide the geometries and insert data
    EXECUTE format(
        $SQL$
            INSERT INTO %1$I.%2$I (unique_object_id, geom, fk_code_liste_contextes, libelle, valeur)
            SELECT %8$I, ST_Multi(ST_Subdivide(geom)), %3$L, %4$I, %5$I
            FROM %6$I.%7$I
        $SQL$,
        target_schema,
        target_table,
        code_context,
        label_field,
        value_field,
        temp_schema,
        temp_table,
        unique_id_field
    );

    RETURN json_build_object(
            'status', 'success',
            'message', 'ok'
        );

END;
$_$;


-- FUNCTION import_data_from_temporary_tables(temp_schema text, temp_table text, label_field text, value_field text, unique_id_field text, code_context text)
COMMENT ON FUNCTION desimper.import_data_from_temporary_tables(temp_schema text, temp_table text, label_field text, value_field text, unique_id_field text, code_context text) IS 'Import data from temporary tables into schema and table defined in desimper.liste_contextes';


--
-- PostgreSQL database dump complete
--



