--
-- PostgreSQL database dump
--






SET statement_timeout = 0;
SET lock_timeout = 0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

;

-- communes
CREATE TABLE desimper.communes (
    id integer NOT NULL,
    code_insee text NOT NULL,
    libelle text NOT NULL,
    geom geometry(MultiPolygon,2154) NOT NULL
);


-- communes
COMMENT ON TABLE desimper.communes IS 'Table des communes';


-- communes_id_seq
ALTER TABLE desimper.communes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.communes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- contextes_projets
CREATE TABLE desimper.contextes_projets (
    id integer NOT NULL,
    fk_id_projet integer NOT NULL,
    geom geometry(MultiPolygon,2154) NOT NULL,
    surface_m numeric(15,2) NOT NULL,
    cree_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    modifie_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    fk_cree_par integer NOT NULL,
    fk_modifie_par integer,
    code_contexte text,
    id_objet_contexte integer
);


-- contextes_projets
COMMENT ON TABLE desimper.contextes_projets IS 'Table des contextes associés aux projets';


-- contextes_projets_id_seq
ALTER TABLE desimper.contextes_projets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.contextes_projets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- liste_contextes
CREATE TABLE desimper.liste_contextes (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL,
    description text NOT NULL,
    type_geom text NOT NULL,
    type_valeur text NOT NULL,
    nom_table character varying(50),
    nom_schema character varying(50)
);


-- liste_contextes
COMMENT ON TABLE desimper.liste_contextes IS 'Table listant l''ensemble des contextes et leurs caractéristiques';


-- liste_contextes_id_seq
ALTER TABLE desimper.liste_contextes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.liste_contextes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- metadata
CREATE TABLE desimper.metadata (
    id integer NOT NULL,
    me_version text NOT NULL,
    me_version_date date NOT NULL,
    me_status smallint NOT NULL
);


-- metadata
COMMENT ON TABLE desimper.metadata IS 'DO NOT DROP THIS TABLE ! Metadata of the structure (version and date). Usefull for database structure and glossary data migrations between versions';


-- nomenclature_destinations
CREATE TABLE desimper.nomenclature_destinations (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL
);


-- nomenclature_destinations
COMMENT ON TABLE desimper.nomenclature_destinations IS 'Table des destinations';


-- nomenclature_destinations_id_seq
ALTER TABLE desimper.nomenclature_destinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.nomenclature_destinations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- nomenclature_pollution
CREATE TABLE desimper.nomenclature_pollution (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL
);


-- nomenclature_pollution
COMMENT ON TABLE desimper.nomenclature_pollution IS 'Table des pollutions';


-- nomenclature_pollution_id_seq
ALTER TABLE desimper.nomenclature_pollution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.nomenclature_pollution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- nomenclature_revetements
CREATE TABLE desimper.nomenclature_revetements (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL,
    impermeable boolean
);


-- nomenclature_revetements
COMMENT ON TABLE desimper.nomenclature_revetements IS 'Table des revêtements';


-- nomenclature_revetements_id_seq
ALTER TABLE desimper.nomenclature_revetements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.nomenclature_revetements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- nomenclature_type_projet
CREATE TABLE desimper.nomenclature_type_projet (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL
);


-- nomenclature_type_projet
COMMENT ON TABLE desimper.nomenclature_type_projet IS 'Table des types de projets';


-- nomenclature_type_projet_id_seq
ALTER TABLE desimper.nomenclature_type_projet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.nomenclature_type_projet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- nomenclature_usages_surface
CREATE TABLE desimper.nomenclature_usages_surface (
    id integer NOT NULL,
    code text NOT NULL,
    libelle text NOT NULL
);


-- nomenclature_usages_surface
COMMENT ON TABLE desimper.nomenclature_usages_surface IS 'Table des usages de surface';


-- nomenclature_usages_surface_id_seq
ALTER TABLE desimper.nomenclature_usages_surface ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.nomenclature_usages_surface_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- pluviometrie
CREATE TABLE desimper.pluviometrie (
    id integer NOT NULL,
    geom geometry(Polygon,2154) NOT NULL,
    periode_retour_pluie integer NOT NULL,
    duree integer,
    hauteur_precipitation double precision
);


-- pluviometrie
COMMENT ON TABLE desimper.pluviometrie IS 'Table des pluviometries';


-- pluviometrie_id_seq
ALTER TABLE desimper.pluviometrie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.pluviometrie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- projets
CREATE TABLE desimper.projets (
    id integer NOT NULL,
    libelle text NOT NULL,
    fk_type_projet text DEFAULT 'CRE'::text NOT NULL,
    fk_destination text DEFAULT 'AUT'::text NOT NULL,
    fk_pollution text DEFAULT 'NON'::text NOT NULL,
    fk_commune_principale text DEFAULT '13001'::text NOT NULL,
    geom geometry(MultiPolygon,2154) NOT NULL,
    cree_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    modifie_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    fk_cree_par integer DEFAULT 1 NOT NULL,
    fk_modifie_par integer DEFAULT 1 NOT NULL
);


-- projets
COMMENT ON TABLE desimper.projets IS 'Table des projets';


-- projets_id_seq
ALTER TABLE desimper.projets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.projets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- surfaces_projet
CREATE TABLE desimper.surfaces_projet (
    id integer NOT NULL,
    fk_id_projet integer NOT NULL,
    fk_id_variante integer NOT NULL,
    surface_m numeric(15,2) NOT NULL,
    geom geometry(MultiPolygon,2154) NOT NULL,
    fk_usages_surface text NOT NULL,
    fk_revetements text NOT NULL,
    cree_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    modifie_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    fk_cree_par integer DEFAULT 1 NOT NULL,
    fk_modifie_par integer DEFAULT 1 NOT NULL
);


-- surfaces_projet
COMMENT ON TABLE desimper.surfaces_projet IS 'Table des surfaces du projet';


-- surfaces_projet_id_seq
ALTER TABLE desimper.surfaces_projet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.surfaces_projet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- variantes
CREATE TABLE desimper.variantes (
    id integer NOT NULL,
    fk_id_projet integer NOT NULL,
    libelle text NOT NULL,
    etat_initial boolean DEFAULT true NOT NULL,
    cree_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    modifie_le timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    fk_cree_par integer DEFAULT 1 NOT NULL,
    fk_modifie_par integer DEFAULT 1 NOT NULL
);


-- variantes
COMMENT ON TABLE desimper.variantes IS 'Table des variantes. Une variante correspond à une "version" d''un projet';


-- variantes_id_seq
ALTER TABLE desimper.variantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME desimper.variantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--



